'''Print common command line commads'''

commands = {
'pwd': 'print working directory',
'hostame': 'computers network name',
'mkdir': 'make a directory',
'cd': 'change directory',
'cd ~': 'go to home directory',
'cd -': 'go to last directory',
'cd ../': 'go up one directory (two directories: cd ../../)',
'ls': 'list current directory',
'rmdir': 'remove directory (must be empty)',
'rm -rf': 'force remove a directory (hidden files may prevent rmdir from working)',
'pushd': 'push directory (saves the current working directory so it can be returned to at any time)',
'popd': 'pop directory (returns to the path at the top of the directory stack.)',
'dirs': 'used with pushd and popd to see which directories are on the stack',
'cp': 'copy a file or directory',
'mv': 'move (or rename) a file or directory',
'less': 'page through a file',
'cat': 'print the whole file',
'xargs': 'execute arguments - construct argument lists and and execute utility',
'find': 'find files',
'grep': 'find things inside files',
'man': 'read a manual page',
'apropos': 'find what man page is appropriate',
'env': 'look at your environment',
'echo': 'print some arguments',
'export': 'export/set a new environment variable',
'exit': 'exit the shell',
'sudo': 'super user root - BE CAREFUL!',
'rm': 'remove - BE CAREFUL!',
'mkdir temp/stuff': 'will only make the directory stuff if it can find the directory temp',
'mkdir -p temp/stuff': "will create the temp and stuff directory directories, provided they don't already exist",
'mkdir "Python Books"': 'use quotes to identify file names with spaces',
'help': 'will open a help file if it exists (for example: brew help, pip3 help)',
'which': 'shows the path to where something lives (for example: which brew, which python3)',
'ls -al': 'lists everything in the current directory with details',
'man ls': 'commands manual (q to exit from the manual)',
'touch': 'makes a file if it does not exist (touch test.txt)',
'open': 'opens a file or directory',
'mdfind': 'search for files or folders',
'open .': 'opens a finder window at the current directory',
'mdfind -name test -onlyin Documents': "searches for files or folders with the word 'test', in the directory called Documents",
'cp file1.txt file2.txt': 'copies file1 and creates file2',
'cp file1.txt backup/': 'creates a copy of file1 in a directory called backup',
'cp -r Notes Notes_copy': 'duplicates the Notes directory and its contents as Notes_copy',
'mv file.txt Notes': 'moves file.txt into the Notes directory',
'mv Notes Stuff': "essentially renames the Notes directory as stuff (is actually creating a new dir)",
'less test.txt': 'displays the file in chunks (q to exit)',
'cat test.txt': 'displays the file as one log blob (q to exit)',
'chmod': 'change file access permissions',
'chown': 'change the owner and group of a file',
'clear': 'clear the terminal display',
'history n': 'shows the previous (n=number) commands',
'rm -i': 'remove with a confirmation',
'rm -r': 'remove a directory and its contents',
'rm -f': 'force remove file without confirmation',
'rmdir': 'remove an empty directory',
'whatis': 'gives a one line description of a command (whatis chown)',
'alias wa="whatis"': 'create keyboard shortcuts for common commands',
'grep i mountains': 'searched for mountains, case insensitive',
'grep -R': 'searches for files in directories that are within other directories (by default grep only searches the current directory, not sub directories)',
'info': 'reports information on a command (info python3, info dirs)',
'--help': 'type this after a command to see the help (try git push -u --help)',
'su - jessica': 'switch user to username',
'lsb_release -a': 'obtain information specific to your Linux distribution'
}


for key in sorted(commands):
    print(f'{key} | {commands[key]}')
